Apimon playbook for cbr
opentelekomcloud-infra/apimon-tests pull request #102
Opened 2024-10-02 13:22 UTC by jmiskani

created playbook for cbr

2024-11-11 07:42 UTC, vladimirhasko requested changes

2024-11-11 07:42 UTC, vladimirhasko commented on playbooks/scenario47_cbr.yaml
> +      - name: Get Availability zones
you don't use it anywhere, so why you have it here?

2024-11-11 07:42 UTC, vladimirhasko commented on playbooks/scenario47_cbr.yaml
> +      - name: Query backups vor CBR vault
for?

2024-11-11 07:42 UTC, vladimirhasko commented on playbooks/scenario47_cbr.yaml
> +      - name: Pause for 3 minutes to complete ECS restoration
please create in otc ansible collection and in python-otcextensions issue requesting wait for restore completion method

2024-11-11 12:59 UTC, jmiskani commented on playbooks/scenario47_cbr.yaml
> +      - name: Query backups vor CBR vault
corrected

2024-11-19 10:41 UTC, vladimirhasko requested changes

2024-11-19 10:41 UTC, vladimirhasko commented on playbooks/scenario47_cbr.yaml
> +            - name: Delete KP
Delete Keypair

2024-11-19 10:41 UTC, vladimirhasko commented on playbooks/scenario47_cbr.yaml
> +      - name: Create Backup Policy
Create CBR Backup Policy

2024-11-19 10:41 UTC, vladimirhasko commented on playbooks/scenario47_cbr.yaml
> +      - name: Associate resouces CBR vault
Associate resources to CBR vault

2024-11-19 10:41 UTC, vladimirhasko commented on playbooks/scenario47_cbr.yaml
> +      - name: Get backup ID
Get CBR backup ID

2024-11-19 10:41 UTC, vladimirhasko commented on playbooks/scenario47_cbr.yaml
> +            - name: Delete Backup Vault
Delete CBR server Backup Vault

2024-11-19 10:41 UTC, vladimirhasko commented on playbooks/scenario47_cbr.yaml
> +      - name: Create restore point
Create CBR restore point

2024-11-19 10:41 UTC, vladimirhasko commented on playbooks/scenario47_cbr.yaml
> +      - name: Restore ECS server from backup
Restore ECS server from CBR backup

2024-11-19 11:38 UTC, jmiskani commented on playbooks/scenario47_cbr.yaml
> +            - name: Delete KP
updated

2024-11-19 11:38 UTC, jmiskani commented on playbooks/scenario47_cbr.yaml
> +      - name: Create Backup Policy
updated

2024-11-19 11:38 UTC, jmiskani commented on playbooks/scenario47_cbr.yaml
> +      - name: Associate resouces CBR vault
updated

2024-11-19 11:39 UTC, jmiskani commented on playbooks/scenario47_cbr.yaml
> +      - name: Get backup ID
updated

2024-11-19 11:40 UTC, jmiskani commented on playbooks/scenario47_cbr.yaml
> +            - name: Delete Backup Vault
updated

2024-11-19 11:40 UTC, jmiskani commented on playbooks/scenario47_cbr.yaml
> +      - name: Create restore point
updated

2024-11-19 11:41 UTC, jmiskani commented on playbooks/scenario47_cbr.yaml
> +      - name: Restore ECS server from backup
updated

2024-11-19 15:07 UTC, vladimirhasko approved these changes

2024-11-19 15:12 UTC, merged