Add scenario45 - DMS Kafka instance
opentelekomcloud-infra/apimon-tests pull request #78
Opened 2024-02-15 11:41 UTC by danielaebert

Create, List, Update, Delete DMS Kafka instance.

2024-03-18 09:38 UTC, vladimirhasko requested changes

2024-03-19 09:29 UTC, danielaebert commented on playbooks/scenario45_dms_inst.yaml
> +          storage_space: '600'
Quotes removed

2024-03-25 13:56 UTC, anton-sidelnikov requested changes

2024-04-04 10:30 UTC, danielaebert commented on playbooks/scenario45_dms_inst.yaml
> +                 seconds: 30
Unfortunately not.
The instance is deleted properly. checking the status returns "no instance found".
But the SG is still busy. I do not see another workaround than adding a pause statement.
Anyway, I have opened a bug for that:
https://jira.tsi-dev.otc-service.com/browse/BM-4558

2024-04-23 10:15 UTC, anton-sidelnikov submitted a review, later dismissed

2024-04-24 10:58 UTC, anton-sidelnikov approved these changes

2024-04-25 13:23 UTC, vladimirhasko requested changes

2024-04-25 13:23 UTC, vladimirhasko commented on playbooks/scenario45_dms_inst.yaml
> +            - "100.125.4.25"
please check whether this is mandatory parameter.
If not you can remove dns_list at all

2024-05-15 09:05 UTC, danielaebert commented
New issue for DMS wait/timeout problem created:
https://github.com/opentelekomcloud/ansible-collection-cloud/issues/336

2024-05-15 09:05 UTC, vladimirhasko approved these changes

2024-05-15 09:14 UTC, merged